# Generated by Django 4.1.7 on 2023-06-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="follower_count",
            new_name="subscriber_count",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="following_count",
            new_name="subscription_count",
        ),
    ]
